services:
 mysql-container:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: admin
  ports:
   - 3306:3306
  volumes:
   - ./mysql-init:/docker-entrypoint-initdb.d
  networks:
   -  ecommerce-network
  hostname: mysql-host-productsmicroservice

 products-microservice:
  image: ecommerce-solution.product-service:v1.0.0
  environment:
   MYSQL_HOST: mysql-host-productsmicroservice
   MYSQL_PASSWORD: admin
  ports:
   - 8080:8080
  networks:
   -  ecommerce-network
  
 postgres-container:
  image: postgres:latest
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: eCommerceUsers
  ports:
   - 5432:5432
  volumes:
   - ./postgres-init:/docker-entrypoint-initdb.d
  networks:
   - ecommerce-network
  
 users-microservice:
  image: ecommerce-solution.user-service:v1.0.0
  environment:
   POSTGRES_HOST: postgres-container
   POSTGRES_PASSWORD: admin
  ports:
   - 9090:9090
  networks:
   - ecommerce-network

networks:
 ecommerce-network:
  driver: bridge